API_HOST_URL: 'http://app.e-numeracy.com' # localhost is 10.0.2.2 in Android
ENVIRONMENT_DISPLAY_NAME: 'Localhost'
PLATFORM_NAME: 'E-Numeracy'
PLATFORM_DESTINATION_NAME: 'e-numeracy.com'
FEEDBACK_EMAIL_ADDRESS: 'support@e-numeracy.com'
